### ISSUE TITLE
Physical screen automatic zoom

### ISSUE THREAD

**Issue by misthero** [skepickle/foundryvtt-gaming-table-player#18]
Hello, thanks for the module, what would you think about an option to automatically zoom to the "VTT player"'s screen size?

In a physical gaming table scenario would be easier entering the screen witdh and the size of the square in mm (or inches) to auto calculate the required zoom level to get the grid of the proper size.

**Comment by misthero** [comment]
Made a PR but there was an error 👍

**Comment by misthero** [comment]
well I already had a reworked version ready locally, you got the new pr if intrested. Also there is an extra feature to show what the other screen is viewing right now if you want.

**Comment by skepickle** [comment]
Okay, I see what you had submitted in PR #19. It wasn't quite right because of the nuance between using the GM's screen resolution vs using the Gaming Table player's screen resolution. I think it can be adapted to work against the right screen. Do you mind if I put you as a reviewer when I get a PR up to address this enhancement request?

**Comment by skepickle** [comment]
I see you also submitted PR #21 with some further enhancements. There's interesting stuff in that one as well. I'll look over it and see how I'd like to pull it all in together in a way that won't conflict with some other changes I have planned. Thanks!
