### ISSUE TITLE
Do not pan to token option buggy

### ISSUE THREAD

**Issue by misthero** [skepickle/foundryvtt-gaming-table-player#33]
The behaviour is erratic, when moving the vtt owned token around with the mouse the view jumps to the token, than goes back to original position, sometime it keeps the wrong position looks like random..

https://github.com/skepickle/foundryvtt-gaming-table-player/assets/3662610/994b00b9-28ed-4cf4-9b96-448f25e63be7

**Comment by skepickle** [comment]
Are you moving the token AS the gaming table player? Or is GM moving the token? The module kind-of assumes that nobody is directly using the gaming table user's session. It's meant to be controlled remotely via the GM's session

**Comment by misthero** [comment]
was moving from the player screen.

**Comment by skepickle** [comment]
The refocus to the original target location for the gaming table happens as the interval defined in the "Refresh Period (in ms)". I cannot safely create a hook on "canvasPan" because it will cause a feedback loop. Instead, at the refresh interval, if the Gaming Table Player's view is not at the correct place, it is recentered. I don't count this as buggy, but rather the intended behavior. If you could elaborate on what behavior here seems wrong to you, I would appreciate it.

I haven't been able to reproduce the viewport not correcting itself... For me, it always recenters to where the GM indicated last for the active scene.

**Comment by skepickle** [comment]
@misthero Can you try the code on branch `33-do-not-pan-to-token-option-buggy`? I'm not sure if this makes the behavior less "buggy"... but it's trying to add a hook onto the `canvasPan` event.

**Comment by skepickle** [comment]
I still _really_ don't like the idea of having a Hook on canvasPan issuing another pan command. There's so many chances for race conditions...

**Comment by misthero** [comment]
I think understand what you mean, I hadn't time to test it yet.

Don't know if can this be useful, but have you considered using a debounce method for the timeout? 

To avoid the timeout to start again before it has completed the previous timeout you can name it unsing a variable and clear it if it's called again before the previous timeout has completed.

Or... I think foundry already has a debounce method: https://foundryvtt.com/api/v12/functions/foundry.utils.debounce.html

**Comment by skepickle** [comment]
I tried the debounce, and it didn't help. I have basically found no good way of fixing this. I'm going to close the issue because it's been stale for a while. I am not seeing the issue when not interacting with the Gaming Table's player session... which is the intended use model for this functionality... so I'm not sure how to address this.
